name: Build and Deploy
on:
  # XXX: REMOVE BEFORE PR LANDS
  push:
    branches: [ t3chguy/notarize1 ]
  # Nightly build
  schedule:
    - cron: '0 11 * * *'
  # Manual nightly & release
  workflow_dispatch:
    inputs:
      mode:
        description: What type of build to trigger. Release builds should be ran from the `master` branch.
        required: true
        default: nightly
        type: choice
        options:
          - nightly
          - release
      deploy:
        description: Whether to deploy artifacts
        required: true
        type: boolean
        default: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  DEPLOYMENT_DIR: ${{ inputs.mode == 'release' && 'desktop' || 'nightly' }}
jobs:
  fetch:
    uses: ./.github/workflows/build_prepare.yaml
    with:
      config: element.io/${{ inputs.mode || 'nightly' }}
      version: ${{ inputs.mode == 'release' && '' || 'develop' }}

  macos:
    needs: fetch
    name: macOS
    uses: ./.github/workflows/build_macos.yaml
    secrets: inherit
    with:
      sign: true
      deploy-mode: true
      base-url: https://packages.element.io/${{ env.DEPLOYMENT_DIR }}
      # TODO this needs to be dynamic
      version: 2022121309

  deploy:
    needs:
      - macos
    runs-on: ubuntu-latest
    name: Deploy
    if: github.event != 'workflow_dispatch' || inputs.deploy
    environment: packages.element.io
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: packages.element.io
          path: packages.element.io

      - name: Deploy artifacts
        run: aws s3 cp --recursive packages.element.io/ s3://$R2_BUCKET/$DEPLOYMENT_DIR --endpoint-url $R2_URL --region auto
        env:
          # XXX: UPDATE THIS BEFORE LANDING THE PR
          R2_BUCKET: 'packages-element-io-test'
          R2_URL: ${{ secrets.CF_R2_S3_API }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CF_R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CF_R2_TOKEN }}
